[package]
name = "rust"
version = "0.1.0"
authors = ["kjonson"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns-lookup = "1.0.1"

[[bin]]
name = "traceroute"
path = "src/main.rs"
